spring:
  application:
    name: fire-alarm-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/firedb?options=-c%20timezone=Asia/Ho_Chi_Minh
    username: fireuser
    password: firepassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Ho_Chi_Minh

# MQTT Properties
mqtt:
  broker:
    url: tcp://localhost:1883
  client:
    id: spring-boot-backend-client
  topic:
    telemetry: fire-alarm/telemetry/+
    command: fire-alarm/command/

# InfluxDB Properties
influxdb:
  url: http://localhost:8086
  token: dev-super-secret-token-123
  org: firealarm_org
  bucket: firealarm_bucket
